# Сейчас будем возиться с матрицами и СЛУ
Для этого нам понадобится numpy

In [1]:
import numpy as np

In [15]:
#создаем матрицы

a = np.array([[*range(0, 10)], [*range(1, 11)], [*range(2, 12)]] )
b = np.array([[*range(0, 10)], [*range(1, 11)]]).T #тут транспонирование
print(a, b, sep='\n')

#Перемножаем

a.dot(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]]
[[ 0  1]
 [ 1  2]
 [ 2  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]


array([[285, 330],
       [330, 385],
       [375, 440]])

In [28]:
#определитель

a = [[1, 2, 3], [3, 4, 5], [4, 6, 10]]
np.linalg.det(a)

-4.0

In [29]:
#ранг матрицы
np.linalg.matrix_rank(a)

3

In [30]:
a = [[1, -1, 1], [2, 1, 1], [1, 1, 2]]
b = [[3], [11], [8]]
np.linalg.solve(a, b)

array([[ 4.],
       [ 2.],
       [ 1.]])

In [32]:
#обратная матрица

b = np.linalg.inv(a)
print(b.dot(a))

[[  1.00000000e+00   0.00000000e+00   1.11022302e-16]
 [  2.77555756e-17   1.00000000e+00   0.00000000e+00]
 [  0.00000000e+00   0.00000000e+00   1.00000000e+00]]


In [ ]:
_