# Сейчас будем возиться с матрицами и СЛУ
Для этого нам понадобится numpy

In [3]:
import numpy as np

In [4]:
#создаем матрицы

a = np.array([[*range(0, 10)], [*range(1, 11)], [*range(2, 12)]] )
b = np.array([[*range(0, 10)], [*range(1, 11)]]).T #тут транспонирование
print(a, b, sep='\n')

#Перемножаем

a.dot(b)

[[ 0  1  2  3  4  5  6  7  8  9]
 [ 1  2  3  4  5  6  7  8  9 10]
 [ 2  3  4  5  6  7  8  9 10 11]]
[[ 0  1]
 [ 1  2]
 [ 2  3]
 [ 3  4]
 [ 4  5]
 [ 5  6]
 [ 6  7]
 [ 7  8]
 [ 8  9]
 [ 9 10]]


array([[285, 330],
       [330, 385],
       [375, 440]])

In [5]:
#определитель

a = [[1, 2, 3], [3, 4, 5], [4, 6, 10]]
np.linalg.det(a)

-4.0

In [6]:
#ранг матрицы
np.linalg.matrix_rank(a)

3

In [7]:
a = [[1, -1, 1], [2, 1, 10], [1, 1, 2]]
b = [[3], [11], [8]]
np.linalg.solve(a, b)

array([[ 6.07692308],
       [ 2.69230769],
       [-0.38461538]])

In [9]:
#обратная матрица

b = np.linalg.inv(a)
print(b.dot(a))


[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]
